# Generated by Django 5.0.1 on 2024-02-08 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='houseunit',
            name='bedrooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=1),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='house_type',
            field=models.CharField(choices=[('duplex', 'Duplex'), ('condominium', 'Condominium'), ('bungalow', 'Bungalow'), ('apartment', 'Apartment'), ('semi_d', 'Semi-D')], default='apartment', max_length=50),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TechnicianReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='technician_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
