# Generated by Django 5.0.1 on 2024-02-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_bank_account_number_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
