# Generated by Django 5.0.1 on 2024-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_paymentproof_house_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianreport',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
