# Generated by Django 5.0.1 on 2024-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_technicianreport_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
