# Generated by Django 5.0.1 on 2024-02-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_transaction_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented Out')], default='available', max_length=10),
        ),
    ]
