# Generated by Django 5.0.1 on 2024-02-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cohome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
